# Generated by Django 4.0.5 on 2022-06-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adocao", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adocao",
            options={"verbose_name_plural": "Adoções"},
        ),
    ]
